apiVersion: v1
kind: Pod
metadata:
  name: kezdo-app
  labels:
    app: kezdo
spec:
  containers:
  - name: kontener
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
